// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VLCk5CQHhWYH3_rGEpfKc9n_W5QT-0o',
    appId: '1:870914273925:web:9bcfba8f66839c035c6fec',
    messagingSenderId: '870914273925',
    projectId: 'haritha-club-blood-directory',
    authDomain: 'haritha-club-blood-directory.firebaseapp.com',
    storageBucket: 'haritha-club-blood-directory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIrP2ar9kRUYuCxV5tpmLYBG2soOFQRrQ',
    appId: '1:870914273925:android:84641a3432a2cc2d5c6fec',
    messagingSenderId: '870914273925',
    projectId: 'haritha-club-blood-directory',
    storageBucket: 'haritha-club-blood-directory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfGMR18lMBKeMw_DZZkkr59tJqbtXqOJQ',
    appId: '1:870914273925:ios:0d6c2e893b76aa9f5c6fec',
    messagingSenderId: '870914273925',
    projectId: 'haritha-club-blood-directory',
    storageBucket: 'haritha-club-blood-directory.appspot.com',
    iosClientId: '870914273925-vosbjgnvuqa23l8o24f6p70h9so3l9nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDontaionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfGMR18lMBKeMw_DZZkkr59tJqbtXqOJQ',
    appId: '1:870914273925:ios:0d6c2e893b76aa9f5c6fec',
    messagingSenderId: '870914273925',
    projectId: 'haritha-club-blood-directory',
    storageBucket: 'haritha-club-blood-directory.appspot.com',
    iosClientId: '870914273925-vosbjgnvuqa23l8o24f6p70h9so3l9nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDontaionApp',
  );
}
